org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official

GROUP=ai.giga
VERSION_NAME=0.1.0
POM_ARTIFACT_ID=gigasdk-livekit

POM_NAME=Giga SDK for Android (LiveKit)
POM_DESCRIPTION=Native Android library for Giga voice and chat agent flows built on top of LiveKit.
POM_INCEPTION_YEAR=2024
POM_URL=https://github.com/GigaML/AndroidGigaSDKLivekit/

POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/GigaML/AndroidGigaSDKLivekit/
POM_SCM_CONNECTION=scm:git:https://github.com/GigaML/AndroidGigaSDKLivekit.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/GigaML/AndroidGigaSDKLivekit.git

POM_DEVELOPER_ID=gigaml
POM_DEVELOPER_NAME=GigaML
POM_DEVELOPER_URL=https://github.com/GigaML/
